# Generated by Django 3.0.8 on 2022-04-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
