# Generated by Django 3.0.8 on 2022-04-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0002_auto_20220407_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
