# Generated by Django 3.0.8 on 2022-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unitStock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
